$env:TF_VAR_AWS_ACCESS_KEY_ID = "AWSKEY"
$env:TF_VAR_AWS_SECRET_ACCESS_KEY = "AWSSECRET"

$env:AWS_ACCESS_KEY_ID = "AWSKEY"
$env:AWS_SECRET_ACCESS_KEY = "AWSSECRET"
$env:AWS_DEFAULT_REGION = "us-east-1" # Replace with your desired region

