$env:TF_VAR_AWS_ACCESS_KEY_ID = "AKIAVNZJKRJWRNDUVXNT"
$env:TF_VAR_AWS_SECRET_ACCESS_KEY = "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"

$env:AWS_ACCESS_KEY_ID = "AKIAVNZJKRJWRNDUVXNT"
$env:AWS_SECRET_ACCESS_KEY = "MSrXbUunghGsw2AuwrVfNTDoOU870tHwcakHicvP"
$env:AWS_DEFAULT_REGION = "us-east-1" # Replace with your desired region

